### ISSUE TITLE
instruction information

### ISSUE THREAD

**Issue by peterferrie** [xoreaxeaxeax/sandsifter#12]
0f 18 /4-7 work on a Pentium 3 and later. I assumed that they were 0f 18 /0-3 aliases.

db e0 is feni db e1 is fdisi
df c0 - df c7 is ffreep st(i)
c0/c1/d0/d1/d2/d3 3x/7x/bx/fx are sal r/m, imm8 That's just shl with another name.
f6/f7 /1 is truly an alias for f6/f7 /0.
f1 is icebp.

From the whitepaper:
66e90000 jmpw 4f5
This *is* a four-byte instruction, and it jumps to a 16-bit address (i.e. 0x0000xxxx).
Intel CPUs do this, too.  The disassembler is not wrong.

**Comment by hlide** [comment]
- 0f 18 /4-7: Hintable NOP, See U.S. Patent 5,701,442.
- dbe0 : FENI only for real coprocessor 8087 - enable interrupt; others - same as FNOP (maintained for 8087 retro-compatibility)
- dbe1 : FDISI only for real coprocessor 8087 - disable interrupt; others - same as FNOP (maintained for 8087 retro-compatibility)
- c[0|1],d[0|1|2|3] : SAL as SHL aliases (maintained for 8086 retro-compatibility). See sandpile.org -- IA-32 architecture -- opcode groups
- f6 /1, f7 /1 : TEST aliases (maintained for 8086 retro-compatibility). Christian Ludloff wrote: "While the latest Intel manuals still omit this de-facto standard, the recent x86-64 manuals from AMD document it".
- f1 : INT1, ICEBP. AMD documents it. Christian Ludloff wrote: "Unlike INT 1 (CDh,01h), INT1 (F1h) doesn't perform the IOPL or DPL check and it can't be redirected via the TSS32.IRB".
- e8, e9 :  See sandpile.org. CALL/JMP<sup>Df64</sup> Jz. Df64 stands for "defaults to O64 in PM64; 66h results in O16 in AMD64 but is ignored in EM64T (near branches)".

**Comment by xoreaxeaxeax** [comment]
We may update in the future (sandpile is a useful site) but the goal of the project is really to find instructions that are undocumented by the _manufacturer_; resolving their functionality is an effort for another day.  As for 66 e8/e9 - I believe the paper and slides specify this is for _64 bit code_; every Intel processor I've checked discards the prefix in this case, which is not what disassemblers are doing.
