### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by DirectXMan12** [xoreaxeaxeax/sandsifter#13]
Hi!  Please consider adding some sort of license to this repo,
so that others can properly fork and contribute under clear terms
(and perhaps even package and distribute the code in distro package
managers).

There's a handy guide to choosing a license here if you haven't done so
before: https://choosealicense.com/

**Comment by cprogrammer1994** [comment]
This may also help: https://tldrlegal.com/

**Comment by neuschaefer** [comment]
Seems to be fixed in https://github.com/xoreaxeaxeax/sandsifter/commit/8375e6123d093629e3e4437d7903839fd0742c2a
