### ISSUE TITLE
capstone/capstone.h missing

### ISSUE THREAD

**Issue by Azaretdodo** [xoreaxeaxeax/sandsifter#25]
Hello,

when I do a make on the folder SandSifter it speak about capstone/capstone.h is missing...
And my processor is a i386 also is there the problem ?

Thank you in advance to answer my ask,
Best Regards.

(sorry if my english is bad I am french !)

![capture du 2017-07-31 15 10 49](https://user-images.githubusercontent.com/30596513/28779158-774f6522-7602-11e7-8f3f-91d893b45869.png)

**Comment by Azaretdodo** [comment]
I copy paste in the folder SandSifter-master the capstone.h file and I have again the same problem !

**Comment by abactel** [comment]
It looks like you're running Ubuntu. Try running `sudo apt install libcapstone-dev` to install the capstone C library.

**Comment by Azaretdodo** [comment]
Where that file and that folder must be in sandsifter-master folder (I created a capstone folder for put capstone.h in

**Comment by Azaretdodo** [comment]
abactel your libcapstone-dev is missing after do your command line my computer answer that isn't do the command line
![capture du 2017-07-31 15 21 15](https://user-images.githubusercontent.com/30596513/28779572-ebe9cff2-7603-11e7-87d6-e9a19752f3b2.png)

**Comment by Azaretdodo** [comment]
It doesn't find that It must download

**Comment by Azaretdodo** [comment]
anybody has the repair ?

Thank you for help me !

**Comment by Azaretdodo** [comment]
abactel I download licapstone-dev from debian web site !

**Comment by Azaretdodo** [comment]
when I run the command line of sandsifter It answer that :
![capture du 2017-07-31 15 30 35](https://user-images.githubusercontent.com/30596513/28782613-f53f87b8-760d-11e7-8fb8-77eb299c3547.png)

**Comment by Azaretdodo** [comment]
when I run the commande line of sandsifter :
![capture du 2017-07-31 16 32 33](https://user-images.githubusercontent.com/30596513/28782651-0ff71a4e-760e-11e7-9435-85c105ef40cd.png)

**Comment by poobag** [comment]
It literally says in the readme that you have to install Capstone. This isn't an issue with Sandsifter, it's a problem with your general competence. Get a clue you thick cunt!

**Comment by Azaretdodo** [comment]
I had install capstone-master ;) after in binding folder I do all readme...
I think my i386 processor is the failed...

**Comment by Azaretdodo** [comment]
I download Capstone-master and too I do a pip install ;)

**Comment by Wenzel** [comment]
@Azaretdodo i just `sudo apt-get install libcapstone-dev` on a `Ubuntu 16.04.2 LTS`.

try updating your repo. you don't need to install it from pip, or to download capstone manually.

**Comment by Azaretdodo** [comment]
I need to upgrade my Ubuntu 12.04 lts ?

**Comment by Wenzel** [comment]
Not upgrade, just updating your repos.
`sudo apt-get update`.

It seems that this package is available since `xenial`(Ubuntu 16.04) : https://packages.ubuntu.com/xenial/libcapstone-dev

**Comment by Azaretdodo** [comment]
I will upgrade my system since 12.04 to 16.04 by ISO upgrade because my system unwant to deliver my upgrade by "
![capture du 2017-08-01 18 51 53](https://user-images.githubusercontent.com/30596513/28836846-dd4725de-76ea-11e7-8308-85810ff46dfe.png)
sudo apt-get upgrade !

**Comment by Azaretdodo** [comment]
Ubuntu cannot be installed on my system...
I wil install Xubuntu but It is good with SandSifter ?

**Comment by Azaretdodo** [comment]
Finally Xubuntu doesn't work I will install Lubuntu but for sandsifter is it good ?

**Comment by Azaretdodo** [comment]
on Ubuntu 16.04.3 I can install libcapstone-dev and then do a make but now I have this issue !:
![capture du 2017-08-04 11-03-25](https://user-images.githubusercontent.com/30596513/28962228-474e6a3e-7905-11e7-9b59-6d4098af038a.png)

**Comment by Azaretdodo** [comment]
I have already sifter in sandsifter-master forlder !:
![capture du 2017-08-04 11-24-23](https://user-images.githubusercontent.com/30596513/28962973-b743a672-7907-11e7-8c17-7d8f455613d9.png)

**Comment by abactel** [comment]
Use `./sifter.py`, not just `sifter.py`.

**Comment by Azaretdodo** [comment]
Read all... 
. /sifter.py doesn't work too
...

**Comment by Azaretdodo** [comment]
I do "sudo import *"

**Comment by xoreaxeaxeax** [comment]
sandsifter will work on any of these operating systems.  There should be no need for an upgrade, and no issue with an i386 processor.  The errors seem to show you do not have capstone installed.  Try 'sudo apt-get update' then 'sudo apt-get install libcapstone-dev'.

**Comment by Ranyaws** [comment]
If anyone is still having trouble with missing `capstone.h` try: `sudo apt-get install python-capstone`

**Comment by tandonmitul27** [comment]
> If anyone is still having trouble with missing `capstone.h` try: `sudo apt-get install python-capstone`

Thanks, it worked!
