### ISSUE TITLE
./sifter.py command missing

### ISSUE THREAD

**Issue by Azaretdodo** [xoreaxeaxeax/sandsifter#31]
Hello dear IT worker,

./sifter.py command is missing...
also in sandsifter-master there is a sifter.py too what can I do ?

Thank you in advance to answer my ask.

Best Regards
(I have Ubuntu 16.04.3 on a old system pentium 4 with only one dies !)

**Comment by Azaretdodo** [comment]
![capture du 2017-08-04 11-24-23](https://user-images.githubusercontent.com/30596513/28963595-00b70e00-790a-11e7-9e9b-ab19e8f6be91.png)

**Comment by Azaretdodo** [comment]
![capture du 2017-08-04 11-06-17](https://user-images.githubusercontent.com/30596513/28963613-0d62fa74-790a-11e7-8aef-1b2559addfba.png)

**Comment by xoreaxeaxeax** [comment]
You need to be in the source folder to run the script (in your situation, sandsifter-master).  To fix the capstone errors, you need to install the capstone core, dev libraries, and python bindings, as described at http://www.capstone-engine.org/documentation.html

**Comment by Azaretdodo** [comment]
I need to follow your link for Ubuntu doing and python for nix also need I to run :
$  cd bindings/python
$ sudo make install
 ?

**Comment by Azaretdodo** [comment]
For run sandsifter-Master script need I to run :
$ make 
 ?
