### ISSUE TITLE
sudo make install on capstone-master/bindings/python doesn't work....

### ISSUE THREAD

**Issue by Azaretdodo** [xoreaxeaxeax/sandsifter#34]
Hello dear IT worker,

"sudo make install" on capstone-master/bindings/python doesn't work....
"Make" works but "sudo make install" doesn't works
After I tried the sandsifter-master command line with the same error for sifter.py ...

Thank you in advance to answer my asks,

Best regards.

![capture du 2017-08-07 12-05-25](https://user-images.githubusercontent.com/30596513/29022302-0fc5dff0-7b69-11e7-93b4-8d8c64797092.png)

**Comment by Azaretdodo** [comment]
The error code for command line sandsifter-master : 

dorianrosse@dorianrosse-ThinkPad-T43:~/sandsifter-master$ sudo ./sifter.py --unk --dis --len --sync --tick -- -P1 -t
Traceback (most recent call last):
  File "./sifter.py", line 16, in <module>
    from capstone import *
ImportError: No module named capstone
dorianrosse@dorianrosse-ThinkPad-T43:~/sandsifter-master$

**Comment by Azaretdodo** [comment]
I have already the libcapstone3 and libcapstone-dev on the last version !

**Comment by xoreaxeaxeax** [comment]
It looks like you may need to "sudo apt-get install python-pip".  However, building from source should not be necessary, it should be sufficient to apt-get install libcapstone-dev.  In the future, Capstone specific issues should be opened with the Capstone project instead of the sandsifter project.

**Comment by Azaretdodo** [comment]
I am happy because now sandsifter work the CPU stress :D

**Comment by Azaretdodo** [comment]
The stress found some error but I will send when the stress is finished the log of the stress but there are some repair for the CPU ?

**Comment by abignail** [comment]
there is no repair for the CPU actually
